version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./myapp:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - DATABASE_URL=postgresql://flaskuser:flaskpass@db:5432/flaskdb
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: flaskuser
      POSTGRES_PASSWORD: flaskpass
      POSTGRES_DB: flaskdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

